name: build linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: sudo apt install mingw-w64

      - name: make default
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64 EXE=stockfish_x64 && strip stockfish_x64*

      - name: make modern
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-modern EXE=stockfish_x64_modern && strip stockfish_x64_modern*

      - name: make bmi2
        run: cd src && make clean && make -j build COMP=mingw ARCH=x86-64-bmi2 EXE=stockfish_x64_bmi2 && strip stockfish_x64_bmi2*

      - uses: actions/upload-artifact@v2
        with:
          name: stockfish
          path: src/stockfish* 
